{{- if .Values.deployment.ingress.enabled }}
apiVersion: {{ .Values.versions.ingress }}
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.deployment.ingress.class }}
    {{ if .Values.deployment.tls.enabled }}
    ingress.kubernetes.io/force-ssl-redirect: "true"
    {{ end }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.deployment.ingress.maxRequestSize }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ .Values.deployment.ingress.timeout.connect | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.deployment.ingress.timeout.read | quote }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.deployment.ingress.timeout.send | quote }}
    {{- range $key, $value := .Values.deployment.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}

spec:
  {{ if .Values.deployment.tls.enabled }}
  tls:
    - secretName: {{ required "TLS secret is required!" .Values.deployment.tls.secretName }}
      hosts:
      - {{ .Values.deployment.host | quote }}
  {{ end }}
  rules:
    - host: {{ .Values.deployment.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kong-proxy
                port:
                  number: 8000
{{- end }}
