# Default configuration map for provisioning GraphDB repository.
# To change it, prepare another configuration map and update "graphdb.repositoryConfigmap"
{{- if .Values.deployment.logbackConfigMap }}
apiVersion: {{ .Values.versions.configmap }}
kind: ConfigMap
metadata:
  name: graphdb-logback-configmap
  labels:
    name: graphdb-logback-configmap
data:
  logback.xml: |-
{{ tpl (.Files.Get "files/config/logback.xml" | indent 4) . }}
{{- end }}
